"""Deterministic writing pools for the shared, persisted career timeline.

The wording changes with the application sequence, never with a viewer refresh.
It does not participate in neural decisions or outcome selection.
"""

from app.simulator.states import SimulationStage


STAGE_STATUS: dict[SimulationStage, tuple[str, ...]] = {
    SimulationStage.SEARCHING_FOR_JOB: (
        "Refreshing the job board",
        "Checking whether entry-level still means entry-level",
        "Scanning the next batch of improbable openings",
        "Looking for a role that accepts a very short résumé",
        "Searching for a team with room for one more organism",
        "Sorting listings by optimism, then by salary",
        "Opening another tab in the ongoing job hunt",
        "Hoping the next posting is less ambitious",
    ),
    SimulationStage.VIEWING_JOB: (
        "Reading a suspiciously enthusiastic posting",
        "Checking the requirements against the lifespan",
        "Finding out what the title actually means",
        "Scanning the fine print for surprise meetings",
        "Reviewing the salary, stack, and warning signs",
        "Investigating a very confident job description",
        "Trying to identify the truly entry-level part",
        "Taking a closer look at the next opportunity",
    ),
    SimulationStage.DECIDING_TO_APPLY: (
        "Consulting 166,700 neurons",
        "Weighing the upside against another online form",
        "Letting the connectome deliberate",
        "Calculating whether hope is a transferable skill",
        "Comparing qualifications with available courage",
        "Considering the application from all eye angles",
        "Deciding if this role is worth the buzz",
        "Trying to make a rational career choice",
    ),
    SimulationStage.APPLICATION_SENT: (
        "Application launched into the void",
        "Résumé submitted; confidence still loading",
        "The hiring portal has received a small visitor",
        "Cover letter safely beyond recall",
        "Submit button clicked with determination",
        "One more application added to the tally",
        "Sending a very compact career history",
        "Waiting for the portal to say thank you",
    ),
    SimulationStage.APPLICATION_RESULT: (
        "Awaiting the automated judgment",
        "Refreshing the inbox at a reasonable frequency",
        "Watching the application status stand still",
        "Waiting to hear from somebody with a pulse",
        "Checking whether the résumé made it through",
        "Interpreting silence as an ongoing process",
        "Monitoring the inbox for a tiny breakthrough",
        "Practicing patience against all instincts",
    ),
    SimulationStage.RECRUITER_SCREEN: (
        "Attempting professional small talk",
        "Joining the recruiter call on time",
        "Trying to keep the camera at eye level",
        "Answering questions about long-term goals",
        "Making a first impression with six legs",
        "Discussing availability with unusual precision",
        "Trying not to land on the microphone",
        "Explaining why this role looks exciting",
    ),
    SimulationStage.TECHNICAL_INTERVIEW: (
        "Selecting an algorithm under pressure",
        "Thinking through the problem out loud",
        "Searching for a base case and some composure",
        "Working through a technical question",
        "Letting the neural output pick an answer",
        "Trying to remember what the question asked",
        "Reviewing the choices before committing",
        "Testing a solution in the mind, approximately",
    ),
    SimulationStage.BEHAVIORAL_INTERVIEW: (
        "Demonstrating culture-adjacent behavior",
        "Finding a story about teamwork",
        "Turning lived experience into a STAR answer",
        "Describing a challenge without mentioning glass",
        "Trying to sound collaborative on camera",
        "Explaining how setbacks became growth",
        "Answering the question behind the question",
        "Making a case for a very unusual colleague",
    ),
    SimulationStage.FINAL_RESULT: (
        "The committee is typing…",
        "Waiting for the final email to load",
        "Checking whether the process has another round",
        "Preparing to read the subject line",
        "Holding steady for the last decision",
        "Watching the inbox for a verdict",
        "Considering both possible outcomes",
        "Trying not to refresh the page again",
    ),
}


EVENT_LINES: dict[str, tuple[str, ...]] = {
    "APPLICATION_QUEUED": (
        "The application to {company} is in the overnight queue. The fly is opening another tab.",
        "Hiring is closed for the night at {company}. The job hunt is not.",
        "The résumé for {company} will wait for morning. Another listing awaits.",
        "No interviews after hours. The {company} application can sit in the inbox.",
        "The fly filed {company} under 'check in the morning' and kept searching.",
        "An application to {company} is parked for the day shift.",
        "The {company} hiring process can sleep. The fly has more forms to fill.",
        "Queued for morning review at {company}. Back to the job board.",
    ),
    "HIRING_RESUMED": (
        "The day shift is reviewing the overnight application to {company}.",
        "Morning has arrived. The fly is checking on {company} first.",
        "The {company} application has returned from the overnight queue.",
        "Hiring hours are open again. Next up: {company}.",
        "The inbox is awake, and {company} is back on the radar.",
        "A new morning means the application to {company} can move forward.",
        "The fly reopened the {company} thread when office hours began.",
        "Overnight applications are being reviewed. {company} is up next.",
    ),
    "JOB_FOUND": (
        "Found {title} at {company}. The tab was opened before common sense arrived.",
        "New listing: {company} wants a {title}. The fly is intrigued.",
        "Spotted {title} at {company}. The requirements are being examined with all available eyes.",
        "The job board served up a {title} opening at {company}. Surely this one is different.",
        "Found a {title} role at {company}. The application journey begins again.",
        "{company} is hiring a {title}. The fly has entered the chat.",
        "A fresh {title} posting appeared at {company}. Optimism remains undefeated.",
        "The search found {title} at {company}. First impression: technically a job.",
        "The {title} listing at {company} is open. The fly is reading the small print.",
        "Another opportunity: {title} at {company}. The browser has too many tabs now.",
    ),
    "JOB_VIEWED": (
        "The listing asks for {years} {year_word} of experience. The fly is doing the math.",
        "Required experience: {years} {year_word}. Current qualifications match: {match_pct}%.",
        "The posting requests {years} {year_word} and a straight face. Only one may be possible.",
        "The fly read the entire posting. The experience line says {years} {year_word}.",
        "A {match_pct}% match, with {years} {year_word} requested. The application button remains tempting.",
        "The listing wants {years} {year_word} of experience. Fly lifespans were not considered.",
        "The role's fine print includes: ‘{requirement}.’ The fly pauses.",
        "The qualification meter landed at {match_pct}%. The posting is still open.",
        "The job description has been read, including the request for {years} {year_word} of experience.",
        "The fly reviewed the role and its {years} {year_word} requirement. No promises yet.",
    ),
    "JOB_SKIPPED": (
        "Skipped {company}. Even the fly has boundaries.",
        "{company} did not make the shortlist. The job hunt continues.",
        "The fly closed the listing at {company} without applying. A rare act of restraint.",
        "No application to {company} this time. The neurons voted to keep scrolling.",
        "Passed on {company}. Perhaps the next listing will ask for fewer miracles.",
        "{company} has been skipped. The submit button was spared.",
        "The fly considered {company}, then chose another tab.",
        "No résumé for {company} today. On to the next possibility.",
        "{company} was a no. The fly is calling it strategic selectivity.",
        "The application to {company} never left the nest.",
    ),
    "APPLICATION_SENT": (
        "Applied to {company}. Cover letter addressed to ‘Hiring Organism.’",
        "The résumé reached {company}. The fly is pretending not to watch the inbox.",
        "Application sent to {company}. Six legs, one very small career plan.",
        "{company} now has the fly's résumé. There is no undo button for optimism.",
        "Submitted to {company}. The portal thanked the fly for its interest.",
        "The fly applied to {company}. The cover letter was almost entirely sincere.",
        "Another application is in the queue at {company}. The wings are crossed.",
        "Résumé uploaded for {company}. The fly would like to be considered a team player.",
        "The application to {company} is officially in the system.",
        "{company} received an application from the world's most persistent insect.",
    ),
    "RESUME_SCANNED": (
        "The automated résumé screen finished its pass. No human verdict yet.",
        "The application has entered the screening stage. The fly remains cautiously hopeful.",
        "A résumé scanner reviewed the submission. The inbox is still quiet.",
        "The first filter has seen the résumé. The fly is awaiting news.",
        "Screening complete. The application now lives in the waiting room.",
        "The portal moved the résumé to review. An actual reply is not guaranteed.",
        "The résumé has passed through a machine. It has not emerged with answers.",
        "An automated review ran. The fly is resisting the urge to refresh.",
        "The submission has been scanned. For now, only the status changed.",
        "The first screening step is over. The fly is watching the inbox.",
    ),
    "APPLICATION_GHOSTED": (
        "{company} has entered a committed relationship with silence.",
        "No response from {company}. The inbox is practicing minimalism.",
        "{company} went quiet after the application. The fly has closed the tab.",
        "The application to {company} received the silent treatment.",
        "{company} never replied. The fly is filing that under 'probably no.'",
        "Another unanswered application: {company}. The silence has excellent uptime.",
        "{company} disappeared from the conversation without saying goodbye.",
        "No follow-up from {company}. The fly is moving on, mostly.",
        "The thread with {company} ended before it began.",
        "{company} chose not to answer. The fly chose another job board tab.",
    ),
    "RECRUITER_SCREEN_BOOKED": (
        "{company} scheduled a recruiter screen. The fly is locating a quiet corner.",
        "A recruiter from {company} wants to talk. The webcam is now a concern.",
        "{company} booked a first call. Professional buzzing practice begins.",
        "The fly made it to a recruiter screen with {company}.",
        "A conversation with {company} is on the calendar. The fly has no calendar.",
        "{company} invited the fly to a quick chat of uncertain length.",
        "Recruiter screen unlocked at {company}. Time to look employable on camera.",
        "{company} wants an introduction. The fly is rehearsing its opening line.",
        "The first human round at {company} is scheduled.",
        "The hiring process at {company} has acquired a video call.",
    ),
    "RECRUITER_SCREEN_PASSED": (
        "The recruiter screen with {company} went well enough for another round.",
        "{company} moved the fly past the first call. The technical round awaits.",
        "The fly cleared the recruiter screen at {company} without landing on the webcam.",
        "First conversation with {company}: passed. The algorithm questions are next.",
        "{company} approved another interview. The fly is both thrilled and concerned.",
        "The recruiter at {company} saw enough to schedule a technical challenge.",
        "The fly survived small talk with {company}. Time to face the whiteboard.",
        "{company} advanced the fly to the next round. Confidence briefly spikes.",
        "Recruiter round passed at {company}. No one asked about the wings.",
        "The first call at {company} is over. There will be more questions.",
    ),
    "TECHNICAL_CORRECT": (
        "The fly answered a {category} question correctly. Suspiciously competent.",
        "Correct on {category}. The connectome would like that noted.",
        "The {category} answer was right. The fly appears surprised too.",
        "One correct {category} answer is now on the record.",
        "The technical panel got a correct {category} response from the fly.",
        "A {category} question has been solved. Nobody expected this exact moment.",
        "Correct answer selected for {category}. The wings remain calm.",
        "The fly chose ‘{answer}’ for {category}, and it was right.",
        "The {category} round produced a correct answer. Please remain professional.",
        "A rare clean hit on {category}. The fly is not celebrating yet.",
    ),
    "TECHNICAL_WRONG": (
        "The fly chose ‘{answer}’ for {category}. That was not it.",
        "Incorrect on {category}. The fly would like to revisit the question.",
        "The selected {category} answer was ‘{answer}’. The panel disagreed.",
        "The {category} question did not go to plan. Neither did the plan.",
        "The fly missed a {category} question and is calling it a learning opportunity.",
        "‘{answer}’ was not the correct {category} answer. Noted for next time.",
        "The technical round hit a snag on {category}.",
        "The fly committed to ‘{answer}’ on {category}. The test did not approve.",
        "A {category} miss is now on the record. The fly keeps buzzing.",
        "The answer to that {category} question was elsewhere.",
    ),
    "BEHAVIORAL_ANSWERED": (
        "Asked ‘{prompt}’ The fly answered in a {style} manner.",
        "The prompt was ‘{prompt}’ A {style} response followed.",
        "Behavioral question: ‘{prompt}’ The fly went with {style}.",
        "The fly faced ‘{prompt}’ and responded {style}.",
        "The interviewer asked ‘{prompt}’ The answer was decidedly {style}.",
        "A {style} response to ‘{prompt}’ is now in the interview notes.",
        "‘{prompt}’ produced a {style} answer from the fly.",
        "The fly handled ‘{prompt}’ in a {style} fashion.",
        "For ‘{prompt}’ the connectome selected a {style} approach.",
        "The behavioral round continued with ‘{prompt}’ and a {style} reply.",
    ),
    "OFFER_ACCEPTED": (
        "The fly accepted an offer from {company}. The career timeline immediately continues.",
        "Offer accepted at {company}. A tiny victory for a very persistent applicant.",
        "{company} offered; the fly accepted. Someone update the résumé.",
        "The fly said yes to {company}. Onward to the next improbable chapter.",
        "Accepted an offer from {company}. Six legs, one signed-up employee.",
        "A yes from {company}, and a yes from the fly. The streak is broken.",
        "The fly accepted the offer from {company}. Please allow one moment of buzzing.",
        "An offer from {company} has been accepted. The inbox finally paid off.",
    ),
    "OFFER_REJECTED": (
        "The fly declined an offer from {company}. The search continues on its own terms.",
        "{company} offered a role, but the fly chose to keep looking.",
        "Offer rejected at {company}. Even this applicant has standards.",
        "The fly thanked {company} and declined. The equity may have been vibes.",
        "A rare offer from {company} was turned down. Back to the board.",
        "The fly passed on the offer from {company}. That took more nerve than the interview.",
        "No deal with {company}. The fly has returned to the listings.",
        "The offer from {company} did not survive the final decision.",
    ),
    "REJECTION": (
        "{company} rejected the fly {reason}. Character development continues.",
        "It was a no from {company} {reason}. The fly is reopening the job board.",
        "{company} passed on the fly {reason}. The search has another chapter.",
        "Rejection from {company} {reason}. The fly is still here.",
        "The process ended at {company} {reason}. Next listing, please.",
        "{company} said no {reason}. The résumé remains available for others.",
        "Another no from {company} {reason}. The wings remain operational.",
        "{company} closed the door {reason}. The fly found another tab.",
        "The answer from {company} was no {reason}. No time to dwell.",
        "The fly did not make it through {company} {reason}. Onward.",
    ),
}


def stage_status(stage: SimulationStage, sequence: int) -> str:
    choices = STAGE_STATUS[stage]
    return choices[(sequence - 1) % len(choices)]


def event_line(kind: str, application_id: int, **values: object) -> str:
    choices = EVENT_LINES[kind]
    if "company" in values:
        values["company"] = str(values["company"]).rstrip(".")
    return choices[(application_id - 1) % len(choices)].format(**values)
